# base container
FROM bam/base:latest AS base

# build container
FROM node:slim AS build

ARG APP_NAME

WORKDIR /opt/app/packages/${APP_NAME}

COPY --from=base /opt/app/packages /opt/app/packages

RUN npm run build

# runtime container
FROM nginx

ARG APP_NAME

COPY --from=build /opt/app/packages/${APP_NAME}/dist /usr/share/nginx/html
COPY --from=build /opt/app/packages/${APP_NAME}/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
